/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author nunes
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usr = new javax.swing.JLabel();
        txt_pwd = new javax.swing.JLabel();
        lbl_tit_login = new javax.swing.JLabel();
        lbl_log_usr = new javax.swing.JTextField();
        lbl_log_pwd = new javax.swing.JPasswordField();
        btn_acess = new javax.swing.JButton();
        img_login_sombra = new javax.swing.JLabel();
        img_background_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_usr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_usr.setForeground(new java.awt.Color(255, 255, 255));
        txt_usr.setText("Usuário");
        txt_usr.setToolTipText("");
        getContentPane().add(txt_usr, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        txt_pwd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_pwd.setForeground(new java.awt.Color(255, 255, 255));
        txt_pwd.setText("Senha");
        getContentPane().add(txt_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        lbl_tit_login.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_tit_login.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tit_login.setText("Login");
        getContentPane().add(lbl_tit_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));
        getContentPane().add(lbl_log_usr, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 200, -1));
        getContentPane().add(lbl_log_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 200, -1));

        btn_acess.setBackground(new java.awt.Color(198, 128, 40));
        btn_acess.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_acess.setText("Entrar");
        btn_acess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acessActionPerformed(evt);
            }
        });
        getContentPane().add(btn_acess, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 220, -1));

        img_login_sombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/loginArea.png"))); // NOI18N
        getContentPane().add(img_login_sombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        img_background_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/login.jpg"))); // NOI18N
        getContentPane().add(img_background_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_acessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_acessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acess;
    private javax.swing.JLabel img_background_login;
    private javax.swing.JLabel img_login_sombra;
    private javax.swing.JPasswordField lbl_log_pwd;
    private javax.swing.JTextField lbl_log_usr;
    private javax.swing.JLabel lbl_tit_login;
    private javax.swing.JLabel txt_pwd;
    private javax.swing.JLabel txt_usr;
    // End of variables declaration//GEN-END:variables
}
